---
- name: "copy the package to ec2"
  become: yes
  user: ubuntu
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz
    mode: '0755'

- name: "untar the file"
  become: yes
  user: ubuntu
  shell: tar -zxvf ~/artifact.tar.gz

- name: "start the app"
  become: yes
  user: ubuntu
  shell: |
    npm install;
    pm2 stop default;
    pm2 start npm -- start
