---
- name: "copy the package to ec2"
  become: yes
  copy:
    src: ~/artifact.tar.gz
    dest: ~/artifact.tar.gz
    owner: ubuntu
    mode: '0755'

- name: "untar the file"
  become: yes
  command: tar -xvfz ~/artifact.tar.gz

- name: "start the app"
  become: yes
  command: |
    npm install;
    pm2 stop default
    pm2 start npm -- start
